### ISSUE TITLE
Unable to purchase snipes.

### ISSUE THREAD

**Issue by jmyers022126** [shopgoodwill-sniper/shopgoodwill-auction-sniper#45]
When I attempt to purchase snipes I am not redirected to a secondary page to complete the purchase, the page from which I select my snipe count to purchase ,or membership duration simply closes, and when I navigate back to that same page and click purchase snipes again I am then proved the error code provided in the screenshot. The how did you hear about us page seems to load up just fine.
![Screenshot 2024-09-27 022000](https://github.com/user-attachments/assets/190bd2df-edf5-423f-b948-7b6892d041a2)

I have attempted to purchase the 5 and 10 snipe package and both provide the same error.

I am on Windows 10, I can provide any additional information requested, I appreciate the service you guys have created thanks for you work and prompt response regarding my previous ticket.

**Comment by shopgoodwill-sniper** [comment]
Hi, there seems to be an outage at PayPal, please try again it should be back now...
