### ISSUE TITLE
Getting 404 error

### ISSUE THREAD

**Issue by chuckdav** [shopgoodwill-sniper/shopgoodwill-auction-sniper#46]
Hi,  I was able to get three snipes then I got 404:
404
There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account.

I think maybe I need to pay but can't figure out how to. 

Thank you, Chuck

**Comment by shopgoodwill-sniper** [comment]
Hi Chuck,

Yes, you are correct, that is exactly what is happening, we have already fixed this issue by issuing an update, please update to the latest version to solve the issue. 

You can update to the latest version by simply running the install/update command again on our homepage at http://Snipeable.com

Please let us know if we can be of further assistance.

Thank you,
Customer Service
Snipeable.com
