### ISSUE TITLE
Downloaded new version, life-time license is no longer active

### ISSUE THREAD

**Issue by islandoflotuseaters** [shopgoodwill-sniper/shopgoodwill-auction-sniper#49]
I had been using the older version, but then it stopped working this morning, so finally downloaded the new version, but now it wants me to pay again. Thanks.

**Comment by shopgoodwill-sniper** [comment]
Must have been a really old version, what was your PayPal transaction Id and which license package/price did you purchase?

**Comment by islandoflotuseaters** [comment]
I only bought it earlier this year, used it for a couple of months and then just started using it again a week or so ago. I can go look that all up though.

**Comment by shopgoodwill-sniper** [comment]
Yes, we will need that information because I couldn't find you by your username islandoflotuseaters

**Comment by islandoflotuseaters** [comment]
I don't believe that you used Paypal at that time, because so far I found a receipt from February 8th when this happened before and you had me repurchase and then refunded me, but you used Square at that time. This is actually the third time my life-time license deactivated and the other time you gave me a code.

**Comment by islandoflotuseaters** [comment]
If you want to confirm in your emails or whatever the previous two times were I believe, Issue #11 and Issue #22 on here.

**Comment by islandoflotuseaters** [comment]
I just found the transaction on a credit card statement, it was a direct payment on January 2nd.

**Comment by islandoflotuseaters** [comment]
Just repurchased. Thank you again.

**Comment by shopgoodwill-sniper** [comment]
PayPal charged $9 fee so we could only do refund $240, there was no way we could workaround the $9 fee, but your license is now re-activated so you're all set!

**Comment by islandoflotuseaters** [comment]
That's fine. Thanks.
