### ISSUE TITLE
My 6 month License has been removed after new Bid Sniper Version

### ISSUE THREAD

**Issue by merchantmogul** [shopgoodwill-sniper/shopgoodwill-auction-sniper#51]
Hi, I had paid for a 6 month subscription but after installing the latest update of bid sniper it's forcing me to pay for another subsciption.

Can you please help me re-activate my 6 month subscription that I paid for?

Thanks

**Comment by merchantmogul** [comment]
Here is proof of my 6 month subcription that your team re-activated for me before:
![Screenshot 2024-10-17 224156](https://github.com/user-attachments/assets/e2b5b880-6996-470d-8e24-26f3ad2f6eba)

**Comment by shopgoodwill-sniper** [comment]
Yes, go ahead and purchase it again and we will refund you promptly.

Best regards
Customer Service 
Snipeable.com

**Comment by merchantmogul** [comment]
I have to pay for it again? You can't just provide the license key?

**Comment by shopgoodwill-sniper** [comment]
No, that's the only way...

**Comment by merchantmogul** [comment]
Ok. I just paid for another 6 months. Let me know when you have sent the refund.

thanks

**Comment by shopgoodwill-sniper** [comment]
Ok, Refund sent now...

Please let us know if we can be of further assistance.

Best regards,
Customer Service
Snipeable.com

**Comment by merchantmogul** [comment]
Great. Thanks very much!
