### ISSUE TITLE
Switching computer 

### ISSUE THREAD

**Issue by mkleitman** [shopgoodwill-sniper/shopgoodwill-auction-sniper#53]
Hello I installed the software not knowing I couldn't use it on a different computer but need to change the installation to a different computer and paid for 6 months

**Comment by shopgoodwill-sniper** [comment]
Hi, unfortunately, the license is tied to the original computer, and we do not have the ability to revoke or transfer it. Regrettably, there’s nothing we can do in this case. The only option available is to purchase a new license for your other computer too.

**Comment by mkleitman** [comment]
Can you refund me the money and I'll buy another one ? .....
