### ISSUE TITLE
4 Shopgoodwill.com sniper bids placed but didn't go through!

### ISSUE THREAD

**Issue by francophillips** [shopgoodwill-sniper/shopgoodwill-auction-sniper#57]
Hi,
 I have attached a screenshot that will help illustrate my problem. On 4 different auctions, the one for the red Levi's jeans, the one for the purplish Anne Klein peacoat, the one for the blue Le Creuset skillet, and the one for the WD external hard drive, I placed maximum bids much higher than what the item went for, and somehow my snipe bid never got submitted. With the jeans, I'd bid a maximum of $16.87, and the item sold for $10. With the peacoat, I'd placed a very high maximum bid of $91.57 because I want to give that coat to my daughter as a holiday present. No one else bid on the coat at all, and yet Bid Sniper says I lost it. On the hard drive, the drive sold for $37, while I bid a max of $46.77, and the skillet went for $39.95, while I submitted a maximum bid of $44.87 using your sniper program.

At the very least, I want the bids I've paid for refunded. But what is going on? I have placed other bids that worked well using your program. Why did these bids not go through at all? I will appreciate any help you can give me. I have already lost 3 items that I should've won using the sniper program. It looks like I may get the chance to bid again on the peacoat for my daughter, but it is unlikely to arrive in time for Christmas if I do win it now. Please help. 
-Sincerely, Chet Phillips

<img width="1280" alt="Screen Shot 2024-12-10 at 10 21 41 PM" src="https://github.com/user-attachments/assets/ffd5c133-5709-434a-9f5d-021803ce2311" />

<img width="1280" alt="Screen Shot 2024-12-10 at 10 21 41 PM" src="https://github.com/user-attachments/assets/05573de2-8345-4e79-877b-f308efee4306" />

**Comment by shopgoodwill-sniper** [comment]
Chet head don't come over here with a complaining attitude asking for a refund for your $0.99 snipe, I don't give a f if it didn't work for you or not I will throw you out of here faster than you can blink your stupid eye. As a matter fact, you're blocked already now you have nothing to snipe with you happy now ? Gtfoh!
