### ISSUE TITLE
Cut and paste does not work with MacOS within the browser or externally

### ISSUE THREAD

**Issue by TOPBILL** [shopgoodwill-sniper/shopgoodwill-auction-sniper#58]
Cut and paste does not work with MacOS within the browser or externally. This ends up being a big time waster.  You can see the cut and paste option with a secondary click but nothing pastes. I can't paste the Auction numbers into the browser, I can't cut the item titles so I can paste them in another app or browser to research prices on Ebay. Everything has to be manually typed in.

**Comment by shopgoodwill-sniper** [comment]
Hi TopBill,

Ok, we will change it so the copy/paste works outside the app too...

Best regards,
Technical Support
Snipeable.com

**Comment by shopgoodwill-sniper** [comment]
Hi TopBill,

We just tested the copy/paste feature and it works fine inside and outside the app, we were able to successfully copy and paste from inside the app to outside the app and vice versa so the issue might be isolated with you computer specifically, your copy paste is probably not working on your computer, you could try restarting your computer to see if that will fix your copy paste functionality or search for a solution!

Best regards,
Technical Support
Snipeable.com
